-- CodePlay-owned schema only. Does not modify existing application tables.
begin;
create schema if not exists codeplay_private;
revoke all on schema codeplay_private from public, anon, authenticated;
grant usage on schema codeplay_private to authenticated;

create table if not exists codeplay_private.lessons (
  id text primary key,
  position integer not null unique,
  content jsonb not null
);
create table if not exists codeplay_private.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 60),
  plan text not null default 'free' check (plan in ('free', 'pro')),
  current_lesson text references codeplay_private.lessons(id)
);
create table if not exists codeplay_private.completions (
  user_id uuid not null references codeplay_private.profiles(id) on delete cascade,
  lesson_id text not null references codeplay_private.lessons(id),
  day date not null default (now() at time zone 'UTC')::date,
  primary key (user_id, lesson_id)
);
alter table codeplay_private.lessons enable row level security;
alter table codeplay_private.profiles enable row level security;
alter table codeplay_private.completions enable row level security;
revoke all on all tables in schema codeplay_private from public, anon, authenticated;
-- There are deliberately no direct client table grants or write policies.

create or replace function codeplay_private.profile()
returns jsonb language plpgsql security definer set search_path = '' set timezone = 'UTC'
as $$
declare
  who uuid := auth.uid();
  person codeplay_private.profiles%rowtype;
  completed jsonb; total_xp integer; next_id text; tracks jsonb;
  cursor_day date := current_date; days integer := 0; username text;
begin
  if who is null then raise exception 'login_required' using errcode = '42501'; end if;
  insert into codeplay_private.profiles(id, display_name)
    select who, left(coalesce(nullif(btrim(u.raw_user_meta_data->>'display_name'), ''), split_part(u.email, '@', 1), 'Learner'), 60)
    from auth.users u where u.id = who on conflict(id) do nothing;
  select * into strict person from codeplay_private.profiles p where p.id = who;
  select split_part(u.email, '@', 1) into username from auth.users u where u.id = who;
  select coalesce(jsonb_agg(jsonb_build_object('lesson_id', c.lesson_id, 'day', c.day) order by c.day, c.lesson_id), '[]'::jsonb),
    coalesce(sum((l.content->>'xp')::integer), 0)::integer
    into completed, total_xp from codeplay_private.completions c
    join codeplay_private.lessons l on l.id = c.lesson_id where c.user_id = who;
  select l.id into next_id from codeplay_private.lessons l
    where (l.content->>'track' = 'free' or person.plan = 'pro')
    and not exists(select 1 from codeplay_private.completions c where c.user_id = who and c.lesson_id = l.id)
    order by l.position limit 1;
  select jsonb_object_agg(t.track, jsonb_build_object('completed', t.done, 'total', t.total)) into tracks
    from (select l.content->>'track' as track, count(c.lesson_id) as done, count(*) as total
      from codeplay_private.lessons l left join codeplay_private.completions c on c.lesson_id = l.id and c.user_id = who
      group by l.content->>'track') t;
  if not exists(select 1 from codeplay_private.completions c where c.user_id = who and c.day = cursor_day) then cursor_day := cursor_day - 1; end if;
  while exists(select 1 from codeplay_private.completions c where c.user_id = who and c.day = cursor_day) loop
    days := days + 1; cursor_day := cursor_day - 1;
  end loop;
  return jsonb_build_object('profile', jsonb_build_object('username', username, 'display_name', person.display_name,
    'plan', person.plan, 'current_lesson', person.current_lesson, 'next_lesson', next_id,
    'completed', completed, 'xp', total_xp, 'streak', days, 'tracks', tracks));
end;
$$;

create or replace function codeplay_private.catalog()
returns jsonb language plpgsql security definer set search_path = ''
as $$
declare result jsonb; account jsonb;
begin
  account := codeplay_private.profile()->'profile';
  select jsonb_agg((l.content - array['answer','explanation','prompt','code','hint','options']) ||
    jsonb_build_object('locked', l.content->>'track' = 'pro' and account->>'plan' <> 'pro') order by l.position)
    into result from codeplay_private.lessons l;
  return jsonb_build_object('lessons', result);
end;
$$;

create or replace function codeplay_private.lesson(lesson_id text)
returns jsonb language plpgsql security definer set search_path = ''
as $$
declare item jsonb; account jsonb;
begin
  account := codeplay_private.profile()->'profile';
  select l.content into item from codeplay_private.lessons l where l.id = lesson_id;
  if item is null then raise exception 'lesson_missing' using errcode = 'P0001'; end if;
  if item->>'track' = 'pro' and account->>'plan' <> 'pro' then raise exception 'pro_required' using errcode = '42501'; end if;
  update codeplay_private.profiles set current_lesson = lesson_id where id = auth.uid();
  return jsonb_build_object('lesson', item - array['answer','explanation']);
end;
$$;

create or replace function codeplay_private.correct(item jsonb, submitted jsonb)
returns boolean language plpgsql immutable set search_path = ''
as $$
declare expected jsonb := item->'answer'; value jsonb; choices jsonb; i integer; normalized text;
begin
  if submitted is null or submitted = 'null'::jsonb then return false; end if;
  if item->>'kind' = 'order' then
    return jsonb_typeof(submitted) = 'array' and submitted = expected;
  elsif item->>'kind' = 'project' then
    if jsonb_typeof(submitted) <> 'array' then return false; end if;
    if jsonb_array_length(submitted) <> jsonb_array_length(expected) then return false; end if;
    for i in 0..jsonb_array_length(expected)-1 loop
      value := submitted->i;
      if jsonb_typeof(value) <> 'string' then return false; end if;
      normalized := btrim(replace(value #>> '{}', E'\r\n', E'\n'), E' \t\r\n');
      if not (expected->i @> jsonb_build_array(normalized)) then return false; end if;
    end loop;
    return true;
  end if;
  if jsonb_typeof(submitted) <> 'string' then return false; end if;
  choices := case when jsonb_typeof(expected) = 'array' then expected else jsonb_build_array(expected) end;
  normalized := btrim(replace(submitted #>> '{}', E'\r\n', E'\n'), E' \t\r\n');
  return choices @> jsonb_build_array(normalized);
end;
$$;

create or replace function codeplay_private.answer(lesson_id text, submitted jsonb)
returns jsonb language plpgsql security definer set search_path = '' set timezone = 'UTC'
as $$
declare item jsonb; passed boolean; inserted integer := 0;
begin
  perform codeplay_private.lesson(lesson_id); -- Authorizes the caller and plan first.
  if pg_column_size(submitted) > 16384 then raise exception 'invalid_answer'; end if;
  select l.content into item from codeplay_private.lessons l where l.id = lesson_id;
  passed := codeplay_private.correct(item, submitted);
  if passed then
    insert into codeplay_private.completions(user_id, lesson_id) values(auth.uid(), lesson_id) on conflict do nothing;
    get diagnostics inserted = row_count;
  end if;
  return jsonb_build_object('correct', passed, 'earned', inserted * (item->>'xp')::integer,
    'explanation', item->'explanation') || codeplay_private.profile();
end;
$$;

create or replace function codeplay_private.update_profile(display_name text)
returns jsonb language plpgsql security definer set search_path = ''
as $$
begin
  perform codeplay_private.profile();
  if display_name is null or char_length(btrim(display_name)) not between 1 and 60 then raise exception 'invalid_name'; end if;
  update codeplay_private.profiles p set display_name = btrim(update_profile.display_name) where p.id = auth.uid();
  return codeplay_private.profile();
end;
$$;

-- Exposed RPC wrappers run with the caller's privileges. Only the private,
-- explicitly granted routines elevate privileges, and each checks auth.uid().
create or replace function public.codeplay_status() returns jsonb
language sql stable security invoker set search_path = '' as $$ select '{"schema_version":1}'::jsonb $$;
create or replace function public.codeplay_profile() returns jsonb
language sql security invoker set search_path = '' as $$ select codeplay_private.profile() $$;
create or replace function public.codeplay_catalog() returns jsonb
language sql security invoker set search_path = '' as $$ select codeplay_private.catalog() $$;
create or replace function public.codeplay_lesson(lesson_id text) returns jsonb
language sql security invoker set search_path = '' as $$ select codeplay_private.lesson(lesson_id) $$;
create or replace function public.codeplay_answer(lesson_id text, submitted jsonb) returns jsonb
language sql security invoker set search_path = '' as $$ select codeplay_private.answer(lesson_id, submitted) $$;
create or replace function public.codeplay_update_profile(display_name text) returns jsonb
language sql security invoker set search_path = '' as $$ select codeplay_private.update_profile(display_name) $$;

revoke all on all functions in schema codeplay_private from public, anon, authenticated;
grant execute on function codeplay_private.profile(), codeplay_private.catalog(), codeplay_private.lesson(text),
  codeplay_private.answer(text,jsonb), codeplay_private.update_profile(text) to authenticated;
revoke all on function public.codeplay_status(), public.codeplay_profile(), public.codeplay_catalog(),
  public.codeplay_lesson(text), public.codeplay_answer(text,jsonb), public.codeplay_update_profile(text) from public, anon, authenticated;
grant execute on function public.codeplay_status() to anon, authenticated;
grant execute on function public.codeplay_profile(), public.codeplay_catalog(), public.codeplay_lesson(text),
  public.codeplay_answer(text,jsonb), public.codeplay_update_profile(text) to authenticated;
-- Lesson seed and COMMIT are appended by build_migration.py.

INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-01',0,'{"id": "free-01", "track": "free", "topic": "python", "kind": "quiz", "title": {"en": "Your first print", "fa": "اولین چاپ"}, "prompt": {"en": "Which line prints Hello?", "fa": "کدام خط Hello را چاپ می‌کند؟"}, "code": "", "answer": "print(\"Hello\")", "explanation": {"en": "print() displays a value; text belongs inside quotes.", "fa": "تابع print مقدار را نمایش می‌دهد؛ متن داخل کوتیشن قرار می‌گیرد."}, "hint": {"en": "Choose a function call with quoted text.", "fa": "فراخوانی تابع با متن داخل کوتیشن را انتخاب کن."}, "xp": 50, "options": ["print(\"Hello\")", "echo(\"Hello\")", "print Hello", "Hello.print()"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-02',1,'{"id": "free-02", "track": "free", "topic": "python", "kind": "blank", "title": {"en": "Name your adventurer", "fa": "نام ماجراجو"}, "prompt": {"en": "Fill the gap to store Alex in name.", "fa": "جای خالی را پر کن تا Alex در متغیر name ذخیره شود."}, "code": "name ___ \"Alex\"\nprint(name)", "answer": ["="], "explanation": {"en": "Assignment uses =, while == compares values.", "fa": "انتساب با = انجام می‌شود؛ == برای مقایسه است."}, "hint": {"en": "Use the assignment operator.", "fa": "از عملگر انتساب استفاده کن."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-03',2,'{"id": "free-03", "track": "free", "topic": "python", "kind": "output", "title": {"en": "Count your coins", "fa": "شمارش سکه‌ها"}, "prompt": {"en": "What is printed?", "fa": "چه چیزی چاپ می‌شود؟"}, "code": "coins = 4\nprint(coins + 3)", "answer": ["7"], "explanation": {"en": "4 + 3 evaluates to 7.", "fa": "حاصل ۴ + ۳ برابر ۷ است."}, "hint": {"en": "Add the two numbers.", "fa": "دو عدد را جمع کن."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-04',3,'{"id": "free-04", "track": "free", "topic": "python", "kind": "debug", "title": {"en": "Repair the greeting", "fa": "اصلاح پیام خوشامد"}, "prompt": {"en": "Choose the corrected line.", "fa": "خط اصلاح‌شده را انتخاب کن."}, "code": "print(\"Hello)", "answer": "print(\"Hello\")", "explanation": {"en": "The opening and closing quotes must match.", "fa": "کوتیشن آغاز و پایان باید با هم مطابقت داشته باشند."}, "hint": {"en": "Check the closing quote.", "fa": "کوتیشن پایانی را بررسی کن."}, "xp": 50, "options": ["print(\"Hello\")", "print(Hello)", "print(\"Hello)", "print[\"Hello\"]"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-05',4,'{"id": "free-05", "track": "free", "topic": "python", "kind": "quiz", "title": {"en": "Text or number?", "fa": "متن یا عدد؟"}, "prompt": {"en": "Which value is a string?", "fa": "کدام مقدار رشته است؟"}, "code": "", "answer": "\"42\"", "explanation": {"en": "Quotes make \"42\" text, even though it contains digits.", "fa": "کوتیشن، \"42\" را به متن تبدیل می‌کند، حتی اگر شامل رقم باشد."}, "hint": {"en": "Look for quotes.", "fa": "به دنبال کوتیشن بگرد."}, "xp": 50, "options": ["42", "\"42\"", "4.2", "True"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-06',5,'{"id": "free-06", "track": "free", "topic": "python", "kind": "blank", "title": {"en": "Measure a word", "fa": "اندازه‌ی یک واژه"}, "prompt": {"en": "Complete the function that counts characters.", "fa": "تابعی را کامل کن که تعداد نویسه‌ها را می‌شمارد."}, "code": "print(___(\"Python\"))", "answer": ["len"], "explanation": {"en": "len(\"Python\") is 6.", "fa": "خروجی len(\"Python\") برابر ۶ است."}, "hint": {"en": "The function name has three letters.", "fa": "نام تابع سه حرف دارد."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-07',6,'{"id": "free-07", "track": "free", "topic": "python", "kind": "output", "title": {"en": "Repeat a spell", "fa": "تکرار جادو"}, "prompt": {"en": "Write the output without quotes.", "fa": "خروجی را بدون کوتیشن بنویس."}, "code": "print(\"ha\" * 3)", "answer": ["hahaha"], "explanation": {"en": "Multiplying a string repeats it.", "fa": "ضرب رشته در عدد، آن رشته را تکرار می‌کند."}, "hint": {"en": "Join three copies of ha.", "fa": "سه ha را پشت سر هم قرار بده."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-08',7,'{"id": "free-08", "track": "free", "topic": "python", "kind": "quiz", "title": {"en": "Choose a condition", "fa": "انتخاب شرط"}, "prompt": {"en": "Which comparison checks whether score is at least 10?", "fa": "کدام مقایسه بررسی می‌کند امتیاز حداقل ۱۰ است؟"}, "code": "score = 12", "answer": "score >= 10", "explanation": {"en": ">= means greater than or equal to.", "fa": "علامت >= یعنی بزرگ‌تر یا مساوی."}, "hint": {"en": "Include the boundary value 10.", "fa": "مقدار مرزی ۱۰ را هم در نظر بگیر."}, "xp": 50, "options": ["score > 10", "score >= 10", "score = 10", "score < 10"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-09',8,'{"id": "free-09", "track": "free", "topic": "python", "kind": "blank", "title": {"en": "An alternative path", "fa": "مسیر جایگزین"}, "prompt": {"en": "Complete the branch used when the condition is false.", "fa": "شاخه‌ای را کامل کن که در صورت نادرست بودن شرط اجرا می‌شود."}, "code": "if coins > 5:\n    print(\"Buy\")\n___:\n    print(\"Save\")", "answer": ["else"], "explanation": {"en": "else runs when the if condition is false.", "fa": "وقتی شرط if نادرست باشد، else اجرا می‌شود."}, "hint": {"en": "It pairs with if.", "fa": "این واژه همراه if استفاده می‌شود."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-10',9,'{"id": "free-10", "track": "free", "topic": "python", "kind": "debug", "title": {"en": "Indent the path", "fa": "تورفتگی مسیر"}, "prompt": {"en": "Choose the correct block.", "fa": "بلوک صحیح را انتخاب کن."}, "code": "if True:\nprint(\"Go\")", "answer": "if True:\n    print(\"Go\")", "explanation": {"en": "Python uses indentation to group a block.", "fa": "پایتون از تورفتگی برای مشخص کردن بلوک استفاده می‌کند."}, "hint": {"en": "The body needs indentation.", "fa": "بدنه باید تورفتگی داشته باشد."}, "xp": 50, "options": ["if True:\n    print(\"Go\")", "if True\n    print(\"Go\")", "if True:\nprint(\"Go\")", "if True; print(\"Go\")"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-11',10,'{"id": "free-11", "track": "free", "topic": "python", "kind": "output", "title": {"en": "Read the backpack", "fa": "خواندن کوله‌پشتی"}, "prompt": {"en": "What is printed?", "fa": "چه چیزی چاپ می‌شود؟"}, "code": "bag = [\"key\", \"map\", \"coin\"]\nprint(bag[1])", "answer": ["map"], "explanation": {"en": "List indexes start at zero; index 1 is the second item.", "fa": "شماره‌گذاری لیست از صفر شروع می‌شود؛ اندیس ۱ عنصر دوم است."}, "hint": {"en": "Start counting at zero.", "fa": "شمردن را از صفر آغاز کن."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-12',11,'{"id": "free-12", "track": "free", "topic": "python", "kind": "blank", "title": {"en": "Add a key", "fa": "اضافه کردن کلید"}, "prompt": {"en": "Complete the list method.", "fa": "متد لیست را کامل کن."}, "code": "bag = []\nbag.___(\"key\")\nprint(bag)", "answer": ["append"], "explanation": {"en": "append adds one item at the end of a list.", "fa": "متد append یک عنصر به انتهای لیست اضافه می‌کند."}, "hint": {"en": "Use the method for adding one item.", "fa": "متد اضافه کردن یک عنصر را بنویس."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-13',12,'{"id": "free-13", "track": "free", "topic": "python", "kind": "order", "title": {"en": "Build a loop", "fa": "ساخت حلقه"}, "prompt": {"en": "Arrange the lines to print each item.", "fa": "خطوط را مرتب کن تا هر عنصر چاپ شود."}, "code": "", "answer": [0, 1, 2], "explanation": {"en": "Create the list, start the loop, then indent its body.", "fa": "ابتدا لیست، سپس حلقه و بعد بدنه‌ی دارای تورفتگی را بنویس."}, "hint": {"en": "The list must exist before the loop.", "fa": "لیست باید پیش از حلقه ساخته شده باشد."}, "xp": 50, "options": ["items = [1, 2]", "for item in items:", "    print(item)"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-14',13,'{"id": "free-14", "track": "free", "topic": "python", "kind": "output", "title": {"en": "Three steps", "fa": "سه قدم"}, "prompt": {"en": "Write each printed number on a separate line.", "fa": "هر عدد چاپ‌شده را در خط جداگانه بنویس."}, "code": "for n in range(3):\n    print(n)", "answer": ["0\n1\n2"], "explanation": {"en": "range(3) gives 0, 1, 2; the stop value is excluded.", "fa": "range(3) مقادیر ۰، ۱ و ۲ را می‌دهد؛ حد پایانی شامل نمی‌شود."}, "hint": {"en": "Start at zero and stop before three.", "fa": "از صفر شروع کن و پیش از سه توقف کن."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-15',14,'{"id": "free-15", "track": "free", "topic": "python", "kind": "blank", "title": {"en": "Create a function", "fa": "ساخت تابع"}, "prompt": {"en": "Complete the function definition.", "fa": "تعریف تابع را کامل کن."}, "code": "___ greet():\n    print(\"Hi\")\ngreet()", "answer": ["def"], "explanation": {"en": "def introduces a function definition.", "fa": "واژه‌ی def تعریف تابع را آغاز می‌کند."}, "hint": {"en": "Use the function definition keyword.", "fa": "واژه‌ی کلیدی تعریف تابع را بنویس."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-16',15,'{"id": "free-16", "track": "free", "topic": "python", "kind": "quiz", "title": {"en": "Return a result", "fa": "برگرداندن نتیجه"}, "prompt": {"en": "Which line returns the sum to the caller?", "fa": "کدام خط مجموع را به فراخواننده برمی‌گرداند؟"}, "code": "def add(a, b):\n    # next line", "answer": "return a + b", "explanation": {"en": "return sends a result back; print only displays it.", "fa": "return نتیجه را برمی‌گرداند؛ print فقط آن را نمایش می‌دهد."}, "hint": {"en": "Displaying and returning are different.", "fa": "نمایش دادن با برگرداندن فرق دارد."}, "xp": 50, "options": ["print(a + b)", "return a + b", "a + b = return", "break"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-17',16,'{"id": "free-17", "track": "free", "topic": "python", "kind": "output", "title": {"en": "Call your function", "fa": "فراخوانی تابع"}, "prompt": {"en": "What is printed?", "fa": "چه چیزی چاپ می‌شود؟"}, "code": "def double(n):\n    return n * 2\nprint(double(6))", "answer": ["12"], "explanation": {"en": "The argument 6 replaces n, so the result is 12.", "fa": "آرگومان ۶ جای n قرار می‌گیرد و نتیجه ۱۲ می‌شود."}, "hint": {"en": "Substitute 6 for n.", "fa": "به جای n عدد ۶ بگذار."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-18',17,'{"id": "free-18", "track": "free", "topic": "python", "kind": "blank", "title": {"en": "Read a dictionary", "fa": "خواندن دیکشنری"}, "prompt": {"en": "Fill the gap with a quoted key to print Mina.", "fa": "کلید داخل کوتیشن را بنویس تا Mina چاپ شود."}, "code": "user = {\"name\": \"Mina\"}\nprint(user[___])", "answer": ["\"name\"", "''name''"], "explanation": {"en": "A dictionary retrieves values using keys.", "fa": "دیکشنری مقدارها را با کلید بازیابی می‌کند."}, "hint": {"en": "The only key is name.", "fa": "تنها کلید name است."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-19',18,'{"id": "free-19", "track": "free", "topic": "python", "kind": "debug", "title": {"en": "Convert before adding", "fa": "تبدیل پیش از جمع"}, "prompt": {"en": "Choose the expression that prints 12.", "fa": "عبارتی را انتخاب کن که ۱۲ چاپ می‌کند."}, "code": "age = \"10\"\nprint(age + 2)", "answer": "print(int(age) + 2)", "explanation": {"en": "int converts numeric text to an integer.", "fa": "تابع int متن عددی را به عدد صحیح تبدیل می‌کند."}, "hint": {"en": "Convert age to a number first.", "fa": "ابتدا age را به عدد تبدیل کن."}, "xp": 50, "options": ["print(age + \"2\")", "print(int(age) + 2)", "print(str(age) + 2)", "print(age * 2)"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-20',19,'{"id": "free-20", "track": "free", "topic": "python", "kind": "project", "title": {"en": "Mini project: coin counter", "fa": "پروژه‌ی کوچک: شمارنده‌ی سکه"}, "prompt": {"en": "Fill both gaps to sum the coins and print 10.", "fa": "دو جای خالی را پر کن تا مجموع سکه‌ها محاسبه و ۱۰ چاپ شود."}, "code": "coins = [2, 3, 5]\ntotal = 0\nfor coin in coins:\n    total ___ coin\n___(total)", "answer": [["+="], ["print"]], "explanation": {"en": "The loop adds each coin to total, then print displays the result.", "fa": "حلقه هر سکه را به total اضافه می‌کند و print نتیجه را نمایش می‌دهد."}, "hint": {"en": "Use an addition assignment and an output function.", "fa": "از انتساب جمع و تابع نمایش خروجی استفاده کن."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-21',20,'{"id": "free-21", "track": "free", "topic": "django", "kind": "quiz", "title": {"en": "What is Django?", "fa": "جنگو چیست؟"}, "prompt": {"en": "Choose the best description of Django.", "fa": "بهترین توضیح جنگو را انتخاب کن."}, "code": "", "answer": "web", "explanation": {"en": "Django is a Python framework for building web applications.", "fa": "جنگو چارچوبی در پایتون برای ساخت برنامه‌های وب است."}, "hint": {"en": "Think about websites.", "fa": "به وب‌سایت‌ها فکر کن."}, "xp": 50, "options": [{"value": "web", "label": {"en": "A Python web framework", "fa": "چارچوب وب پایتون"}}, {"value": "editor", "label": {"en": "A text editor", "fa": "ویرایشگر متن"}}, {"value": "os", "label": {"en": "An operating system", "fa": "سیستم‌عامل"}}, {"value": "language", "label": {"en": "A separate programming language", "fa": "یک زبان برنامه‌نویسی جدا"}}]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-22',21,'{"id": "free-22", "track": "free", "topic": "django", "kind": "quiz", "title": {"en": "Request and response", "fa": "درخواست و پاسخ"}, "prompt": {"en": "What does a browser send to a web server?", "fa": "مرورگر چه چیزی به وب‌سرور می‌فرستد؟"}, "code": "", "answer": "request", "explanation": {"en": "The browser sends an HTTP request; the server returns a response.", "fa": "مرورگر درخواست HTTP می‌فرستد و سرور پاسخ برمی‌گرداند."}, "hint": {"en": "It asks the server for a resource.", "fa": "مرورگر یک منبع را از سرور درخواست می‌کند."}, "xp": 50, "options": [{"value": "request", "label": {"en": "A request", "fa": "درخواست"}}, {"value": "database", "label": {"en": "A database", "fa": "پایگاه داده"}}, {"value": "model", "label": {"en": "A model", "fa": "مدل"}}, {"value": "password", "label": {"en": "Every saved password", "fa": "همه‌ی رمزهای ذخیره‌شده"}}]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-23',22,'{"id": "free-23", "track": "free", "topic": "django", "kind": "quiz", "title": {"en": "The big picture", "fa": "تصویر کلی جنگو"}, "prompt": {"en": "Which component describes stored data?", "fa": "کدام بخش ساختار داده‌های ذخیره‌شده را توصیف می‌کند؟"}, "code": "", "answer": "Model", "explanation": {"en": "Models describe data; views handle requests; templates describe presentation.", "fa": "مدل‌ها داده، ویوها پردازش درخواست و قالب‌ها نمایش را توصیف می‌کنند."}, "hint": {"en": "Think of the data layer.", "fa": "به لایه‌ی داده فکر کن."}, "xp": 50, "options": ["Model", "Template", "CSS", "Browser"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('free-24',23,'{"id": "free-24", "track": "free", "topic": "django", "kind": "quiz", "title": {"en": "When to use Django", "fa": "چه زمانی از جنگو استفاده کنیم؟"}, "prompt": {"en": "Which project is a good fit for Django?", "fa": "کدام پروژه برای جنگو مناسب است؟"}, "code": "", "answer": "site", "explanation": {"en": "A site with accounts and stored posts benefits from a web framework.", "fa": "وب‌سایتی با حساب کاربری و نوشته‌های ذخیره‌شده از چارچوب وب بهره می‌برد."}, "hint": {"en": "Look for server-side data.", "fa": "به دنبال داده‌های سمت سرور باش."}, "xp": 50, "options": [{"value": "site", "label": {"en": "A blog with user accounts", "fa": "وبلاگ با حساب کاربری"}}, {"value": "font", "label": {"en": "A font file", "fa": "فایل فونت"}}, {"value": "image", "label": {"en": "A single photo", "fa": "یک عکس"}}, {"value": "cable", "label": {"en": "A network cable", "fa": "کابل شبکه"}}]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-01',24,'{"id": "pro-01", "track": "pro", "topic": "python", "kind": "blank", "title": {"en": "List comprehensions", "fa": "خلاصه‌نویسی لیست"}, "prompt": {"en": "Complete the keyword to double each number.", "fa": "واژه را کامل کن تا هر عدد دو برابر شود."}, "code": "doubles = [n * 2 ___ n in range(4)]", "answer": ["for"], "explanation": {"en": "A comprehension combines an expression and a for clause.", "fa": "خلاصه‌نویسی لیست از عبارت و بخش for تشکیل می‌شود."}, "hint": {"en": "Use a loop keyword.", "fa": "واژه‌ی حلقه را بنویس."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-02',25,'{"id": "pro-02", "track": "pro", "topic": "python", "kind": "output", "title": {"en": "Filter a list", "fa": "فیلتر کردن لیست"}, "prompt": {"en": "Write the printed list.", "fa": "لیست چاپ‌شده را بنویس."}, "code": "print([n for n in range(5) if n % 2 == 0])", "answer": ["[0, 2, 4]"], "explanation": {"en": "Only numbers with remainder zero when divided by 2 remain.", "fa": "فقط عددهایی باقی می‌مانند که با تقسیم بر ۲ باقیمانده‌ی صفر دارند."}, "hint": {"en": "Zero is even too.", "fa": "صفر هم زوج است."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-03',26,'{"id": "pro-03", "track": "pro", "topic": "python", "kind": "blank", "title": {"en": "Handle invalid input", "fa": "مدیریت ورودی نامعتبر"}, "prompt": {"en": "Name the exception raised here.", "fa": "نام استثنای ایجادشده را بنویس."}, "code": "try:\n    int(\"hello\")\nexcept ___:\n    print(\"Invalid\")", "answer": ["ValueError"], "explanation": {"en": "int cannot parse hello and raises ValueError.", "fa": "تابع int نمی‌تواند hello را تبدیل کند و ValueError ایجاد می‌کند."}, "hint": {"en": "The type is valid, but its value is unsuitable.", "fa": "نوع درست است ولی مقدار مناسب نیست."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-04',27,'{"id": "pro-04", "track": "pro", "topic": "python", "kind": "order", "title": {"en": "A small class", "fa": "یک کلاس کوچک"}, "prompt": {"en": "Arrange the class, method and body.", "fa": "کلاس، متد و بدنه را مرتب کن."}, "code": "", "answer": [0, 1, 2], "explanation": {"en": "The method belongs inside the class, and its body inside the method.", "fa": "متد داخل کلاس و بدنه داخل متد قرار می‌گیرد."}, "hint": {"en": "Indentation shows nesting.", "fa": "تورفتگی تودرتویی را نشان می‌دهد."}, "xp": 50, "options": ["class Hero:", "    def greet(self):", "        return \"Hello\""]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-05',28,'{"id": "pro-05", "track": "pro", "topic": "python", "kind": "debug", "title": {"en": "Avoid shared defaults", "fa": "پرهیز از مقدار پیش‌فرض مشترک"}, "prompt": {"en": "Choose the safer default for a mutable list parameter.", "fa": "مقدار پیش‌فرض امن‌تر برای پارامتر لیست را انتخاب کن."}, "code": "def collect(items=[]):\n    items.append(\"coin\")\n    return items", "answer": "None", "explanation": {"en": "Use None, then create a new list inside the function when needed.", "fa": "از None استفاده کن و در صورت نیاز داخل تابع یک لیست تازه بساز."}, "hint": {"en": "Do not reuse one list across calls.", "fa": "یک لیست را بین فراخوانی‌ها مشترک نکن."}, "xp": 50, "options": ["None", "[]", "{}", "list()"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-06',29,'{"id": "pro-06", "track": "pro", "topic": "python", "kind": "project", "title": {"en": "Mini project: inventory", "fa": "پروژه‌ی کوچک: موجودی"}, "prompt": {"en": "Complete the dictionary update and return statement.", "fa": "به‌روزرسانی دیکشنری و عبارت برگرداندن را کامل کن."}, "code": "def add_coin(bag):\n    bag[\"coin\"] = bag.___(\"coin\", 0) + 1\n    ___ bag", "answer": [["get"], ["return"]], "explanation": {"en": "get supplies a default for a missing key; return sends the updated bag back.", "fa": "متد get برای کلید ناموجود مقدار پیش‌فرض می‌دهد و return کوله‌ی به‌روز را برمی‌گرداند."}, "hint": {"en": "Use a dictionary lookup with a default.", "fa": "از خواندن دیکشنری با مقدار پیش‌فرض استفاده کن."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-07',30,'{"id": "pro-07", "track": "pro", "topic": "django", "kind": "quiz", "title": {"en": "Start a Django project", "fa": "شروع پروژه‌ی جنگو"}, "prompt": {"en": "Which command creates a project named config?", "fa": "کدام دستور پروژه‌ای به نام config می‌سازد؟"}, "code": "", "answer": "django-admin startproject config", "explanation": {"en": "startproject creates project configuration; startapp creates an app.", "fa": "دستور startproject تنظیمات پروژه و startapp یک اپ می‌سازد."}, "hint": {"en": "Create the project before its apps.", "fa": "پروژه را پیش از اپ‌هایش بساز."}, "xp": 50, "options": ["django-admin startproject config", "django-admin startapp config", "python config.py", "pip start config"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-08',31,'{"id": "pro-08", "track": "pro", "topic": "django", "kind": "blank", "title": {"en": "Create an app", "fa": "ساخت اپ"}, "prompt": {"en": "Complete the command for a blog app.", "fa": "دستور ساخت اپ blog را کامل کن."}, "code": "python manage.py ___ blog", "answer": ["startapp"], "explanation": {"en": "startapp generates a Django application skeleton.", "fa": "دستور startapp ساختار اولیه‌ی یک اپ جنگو را می‌سازد."}, "hint": {"en": "It is not startproject.", "fa": "این دستور startproject نیست."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-09',32,'{"id": "pro-09", "track": "pro", "topic": "django", "kind": "blank", "title": {"en": "Return an HTTP response", "fa": "برگرداندن پاسخ HTTP"}, "prompt": {"en": "Complete the response class.", "fa": "کلاس پاسخ را کامل کن."}, "code": "from django.http import HttpResponse\n\ndef home(request):\n    return ___(\"Hello\")", "answer": ["HttpResponse"], "explanation": {"en": "A view returns a response object.", "fa": "ویو یک شیء پاسخ برمی‌گرداند."}, "hint": {"en": "Use the imported class.", "fa": "از کلاس واردشده استفاده کن."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-10',33,'{"id": "pro-10", "track": "pro", "topic": "django", "kind": "quiz", "title": {"en": "Route to a view", "fa": "اتصال مسیر به ویو"}, "prompt": {"en": "Choose a route that passes the home function to Django.", "fa": "مسیری را انتخاب کن که تابع home را به جنگو می‌دهد."}, "code": "from django.urls import path\nfrom . import views", "answer": "path(\"\", views.home)", "explanation": {"en": "Pass the function itself; Django calls it for each request.", "fa": "خود تابع را بده؛ جنگو آن را برای هر درخواست فراخوانی می‌کند."}, "hint": {"en": "Do not call home while defining the URL.", "fa": "هنگام تعریف مسیر، home را فراخوانی نکن."}, "xp": 50, "options": ["path(\"\", views.home)", "path(\"\", views.home())", "path(views.home, \"\")", "route(\"\", home)"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-11',34,'{"id": "pro-11", "track": "pro", "topic": "django", "kind": "blank", "title": {"en": "Render a template", "fa": "نمایش قالب"}, "prompt": {"en": "Complete the shortcut for rendering HTML.", "fa": "تابع میانبر نمایش HTML را کامل کن."}, "code": "from django.shortcuts import render\n\ndef home(request):\n    return ___(request, \"home.html\", {\"name\": \"Mina\"})", "answer": ["render"], "explanation": {"en": "render combines a template and context into an HTTP response.", "fa": "تابع render قالب و داده‌های context را در یک پاسخ HTTP ترکیب می‌کند."}, "hint": {"en": "Use the imported shortcut.", "fa": "از تابع میانبر واردشده استفاده کن."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-12',35,'{"id": "pro-12", "track": "pro", "topic": "django", "kind": "blank", "title": {"en": "Template variables", "fa": "متغیرهای قالب"}, "prompt": {"en": "Write the variable name inside the template expression.", "fa": "نام متغیر را داخل عبارت قالب بنویس."}, "code": "<h1>Hello, {{ ___ }}</h1>\n<!-- context: {\"name\": \"Mina\"} -->", "answer": ["name"], "explanation": {"en": "Double braces display a context variable, escaped by default.", "fa": "آکولادهای دوتایی متغیر context را نمایش می‌دهند و به‌صورت پیش‌فرض escape می‌کنند."}, "hint": {"en": "Use the context key.", "fa": "کلید context را بنویس."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-13',36,'{"id": "pro-13", "track": "pro", "topic": "django", "kind": "blank", "title": {"en": "Define a model", "fa": "تعریف مدل"}, "prompt": {"en": "Choose the field class for a short title.", "fa": "کلاس فیلد عنوان کوتاه را بنویس."}, "code": "from django.db import models\n\nclass Post(models.Model):\n    title = models.___(max_length=200)", "answer": ["CharField"], "explanation": {"en": "CharField stores short text with a maximum length.", "fa": "فیلد CharField متن کوتاه را با طول حداکثر ذخیره می‌کند."}, "hint": {"en": "This is a character field.", "fa": "این فیلد برای نویسه‌هاست."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-14',37,'{"id": "pro-14", "track": "pro", "topic": "django", "kind": "order", "title": {"en": "Apply schema changes", "fa": "اعمال تغییرات ساختار داده"}, "prompt": {"en": "Arrange the workflow after changing a model.", "fa": "روند پس از تغییر مدل را مرتب کن."}, "code": "", "answer": [0, 1, 2], "explanation": {"en": "Edit the model, generate a migration, then apply it.", "fa": "مدل را تغییر بده، فایل migration بساز و سپس آن را اعمال کن."}, "hint": {"en": "Generate migrations before applying them.", "fa": "migration را پیش از اعمال کردن بساز."}, "xp": 50, "options": ["# Edit models.py", "python manage.py makemigrations", "python manage.py migrate"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-15',38,'{"id": "pro-15", "track": "pro", "topic": "django", "kind": "blank", "title": {"en": "Read published posts", "fa": "خواندن نوشته‌های منتشرشده"}, "prompt": {"en": "Complete the queryset method that selects matching rows.", "fa": "متد انتخاب ردیف‌های مطابق شرط را کامل کن."}, "code": "posts = Post.objects.___(published=True)", "answer": ["filter"], "explanation": {"en": "filter returns a queryset containing rows matching the condition.", "fa": "متد filter مجموعه‌ی ردیف‌های مطابق شرط را برمی‌گرداند."}, "hint": {"en": "You may need multiple matching posts.", "fa": "ممکن است چند نوشته مطابق شرط باشند."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-16',39,'{"id": "pro-16", "track": "pro", "topic": "django", "kind": "quiz", "title": {"en": "Protect a POST form", "fa": "محافظت از فرم POST"}, "prompt": {"en": "Which template tag belongs inside a POST form?", "fa": "کدام تگ قالب باید داخل فرم POST قرار بگیرد؟"}, "code": "<form method=\"post\">\n    <!-- tag here -->\n</form>", "answer": "{% csrf_token %}", "explanation": {"en": "The CSRF token helps Django reject forged state-changing requests.", "fa": "توکن CSRF به جنگو برای رد درخواست‌های جعلیِ تغییر‌دهنده‌ی وضعیت کمک می‌کند."}, "hint": {"en": "Look for the CSRF tag.", "fa": "تگ CSRF را پیدا کن."}, "xp": 50, "options": ["{% csrf_token %}", "{{ password }}", "{% disable_security %}", "<csrf>"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-17',40,'{"id": "pro-17", "track": "pro", "topic": "django", "kind": "blank", "title": {"en": "Validate a form", "fa": "اعتبارسنجی فرم"}, "prompt": {"en": "Complete the method before using cleaned_data.", "fa": "متد را پیش از استفاده از cleaned_data کامل کن."}, "code": "form = PostForm(request.POST)\nif form.___():\n    title = form.cleaned_data[\"title\"]", "answer": ["is_valid"], "explanation": {"en": "is_valid runs field and form validation before cleaned data is used.", "fa": "متد is_valid پیش از استفاده از داده‌ها، فیلدها و فرم را اعتبارسنجی می‌کند."}, "hint": {"en": "Validate before saving.", "fa": "پیش از ذخیره، اعتبارسنجی کن."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-18',41,'{"id": "pro-18", "track": "pro", "topic": "django", "kind": "debug", "title": {"en": "Require authentication", "fa": "الزام ورود"}, "prompt": {"en": "Choose the decorator for a view that requires login.", "fa": "دکوراتور ویویی را انتخاب کن که نیاز به ورود دارد."}, "code": "from django.contrib.auth.decorators import login_required\n\n# decorator here\ndef profile(request):\n    ...", "answer": "@login_required", "explanation": {"en": "login_required redirects anonymous users to the login page.", "fa": "دکوراتور login_required کاربر مهمان را به صفحه‌ی ورود هدایت می‌کند."}, "hint": {"en": "Use the imported decorator.", "fa": "از دکوراتور واردشده استفاده کن."}, "xp": 50, "options": ["@login_required", "@public", "@staff_only", "@csrf_exempt"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-19',42,'{"id": "pro-19", "track": "pro", "topic": "django", "kind": "quiz", "title": {"en": "A missing post", "fa": "نوشته‌ی ناموجود"}, "prompt": {"en": "Which helper returns 404 if the post is missing?", "fa": "کدام تابع اگر نوشته وجود نداشته باشد، ۴۰۴ برمی‌گرداند؟"}, "code": "", "answer": "get_object_or_404(Post, pk=post_id)", "explanation": {"en": "get_object_or_404 gets an object or raises Http404.", "fa": "تابع get_object_or_404 شیء را پیدا می‌کند یا Http404 ایجاد می‌کند."}, "hint": {"en": "Look for the 404 helper.", "fa": "تابع کمکی ۴۰۴ را پیدا کن."}, "xp": 50, "options": ["get_object_or_404(Post, pk=post_id)", "Post.objects.all()", "print(post_id)", "HttpResponse(\"missing\")"]}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
INSERT INTO codeplay_private.lessons(id,position,content) VALUES('pro-20',43,'{"id": "pro-20", "track": "pro", "topic": "django", "kind": "project", "title": {"en": "Mini project: blog page", "fa": "پروژه‌ی کوچک: صفحه‌ی وبلاگ"}, "prompt": {"en": "Complete the query and template shortcut.", "fa": "خواندن داده‌ها و تابع قالب را کامل کن."}, "code": "from django.shortcuts import render\nfrom .models import Post\n\ndef blog(request):\n    posts = Post.objects.___(published=True)\n    return ___(request, \"blog.html\", {\"posts\": posts})", "answer": [["filter"], ["render"]], "explanation": {"en": "The view selects published posts and renders them using a template.", "fa": "ویو نوشته‌های منتشرشده را انتخاب و با قالب نمایش می‌دهد."}, "hint": {"en": "Filter the rows, then render the page.", "fa": "ردیف‌ها را فیلتر کن و صفحه را نمایش بده."}, "xp": 50}'::jsonb) ON CONFLICT(id) DO UPDATE SET position=excluded.position,content=excluded.content;
NOTIFY pgrst, 'reload schema';
COMMIT;
